version: '3.7'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=dbCandidates
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      
volumes:
  mysql_data:
